
[cursor.style]
blinking = "Always"
shape = "Underline"

[font]
size = 14

[font.bold]
family = "FiraCode Nerd Font"
style = "Bold"

[font.bold_italic]
family = "FiraCode Nerd Font"
style = "Bold Italic"

[font.italic]
family = "FiraCode Nerd Font"
style = "Italic"

[font.normal]
family = "FiraCode Nerd font"
style = "Regular"

[window]
opacity = 0.9

[window.padding]
x = 10
y = 5

[general]
import = ["/home/tom/.config/alacritty/alacritty-theme/themes/one_dark.toml"]
