-- Generated by hyprconf2lua v1.4.0
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

-- #######################################################################################

-- AUTOGENERATED HYPRLAND CONFIG.

-- PLEASE USE THE CONFIG PROVIDED IN THE GIT REPO /examples/hyprland.conf AND EDIT IT,

-- OR EDIT THIS ONE ACCORDING TO THE WIKI INSTRUCTIONS.

-- #######################################################################################

-- This is an example Hyprland config file.

-- Refer to the wiki for more information.

-- https://wiki.hyprland.org/Configuring/

-- Please note not all available settings / options are set here.

-- For a full list, see the wiki

-- You can split this configuration into multiple files

-- Create your files separately and then link them to this file like this:

-- source = ~/.config/hypr/myColors.conf

--###############

--## MONITORS ###

--###############

-- See https://wiki.hyprland.org/Configuring/Monitors/

hl.monitor({
    output   = "",
    mode     = "preferred",
    position = "auto",
    scale    = "auto",
})

-- monitor=eDP-1,prefered,auto,auto

-- monitor=DP-2,prefered,auto,auto

--##################

--## MY PROGRAMS ###

--##################

-- See https://wiki.hyprland.org/Configuring/Keywords/

-- Set programs that you use

local terminal = "ghostty"

-- $fileManager = dolphin

local fileManager = "thunar"

local menu = "rofi -show drun"

local emoji = "rofi -modi emoji -show emoji"

local chrome = "google-chrome-stable"

local screenshot = 'grim -g "$(slurp)" - | wl-copy'

local reload_waybar = "killall waybar && waybar"

local starDict = 'sh -c "' .. os.getenv('HOME') .. '/stow/stardict/.stardict/launch_dic.sh"'

local lock = "hyprlock"

--################

--## AUTOSTART ###

--################

-- Autostart necessary processes (like notifications daemons, status bars, etc.)

-- Or execute your favorite apps at launch like this:







-- Stores only text data


-- Stores only image data


--############################

--## ENVIRONMENT VARIABLES ###

--############################

-- See https://wiki.hyprland.org/Configuring/Environment-variables/

hl.env("XCURSOR_SIZE", 24)

hl.env("HYPRCURSOR_SIZE", 24)

--####################

--## LOOK AND FEEL ###

--####################

-- Refer to https://wiki.hyprland.org/Configuring/Variables/

-- https://wiki.hyprland.org/Configuring/Variables/#general

hl.config({
    general = {
        gaps_in = 5,
        gaps_out = 10,
        border_size = 6,
        -- https://wiki.hyprland.org/Configuring/Variables/#variable-types for info about colors
        -- Set to true enable resizing windows by clicking and dragging on borders and gaps
        resize_on_border = false,
        -- Please see https://wiki.hyprland.org/Configuring/Tearing/ before you turn this on
        allow_tearing = false,
        layout = "dwindle",
        col = {
            active_border = { colors = { "rgba(e8dec8ee)", "rgba(576E8Cee)" }, angle = 45 },
            inactive_border = "rgba(595959aa)",
        },
    },
})

-- https://wiki.hyprland.org/Configuring/Variables/#decoration

hl.config({
    decoration = {
        rounding = 10,
        -- Change transparency of focused and unfocused windows
        active_opacity = 1.0,
        inactive_opacity = 1.0,
        shadow = {
            enabled = true,
            range = 4,
            render_power = 3,
            color = "rgba(1a1a1aee)",
        },
        -- https://wiki.hyprland.org/Configuring/Variables/#blur
        blur = {
            enabled = true,
            size = 3,
            passes = 1,
            vibrancy = 0.1696,
        },
    },
})

-- https://wiki.hyprland.org/Configuring/Variables/#animations

hl.config({
    animations = {
        enabled = { true, "please:)" },
        -- Default animations, see https://wiki.hyprland.org/Configuring/Animations/ for more
        bezier = {
            easeOutQuint = { 0.23, 1, 0.32, 1 },
            easeInOutCubic = { 0.65, 0.05, 0.36, 1 },
            linear = { 0, 0, 1, 1 },
            almostLinear = { 0.5, 0.5, 0.75, 1.0 },
            quick = { 0.15, 0, 0.1, 1 },
        },
        animation = {
            global = { 1, 10, "default" },
            border = { 1, 5.39, "easeOutQuint" },
            windows = { 1, 4.79, "easeOutQuint" },
            windowsIn = { 1, 4.1, "easeOutQuint", "popin 87%" },
            windowsOut = { 1, 1.49, "linear", "popin 87%" },
            fadeIn = { 1, 1.73, "almostLinear" },
            fadeOut = { 1, 1.46, "almostLinear" },
            fade = { 1, 3.03, "quick" },
            layers = { 1, 3.81, "easeOutQuint" },
            layersIn = { 1, 4, "easeOutQuint", "fade" },
            layersOut = { 1, 1.5, "linear", "fade" },
            fadeLayersIn = { 1, 1.79, "almostLinear" },
            fadeLayersOut = { 1, 1.39, "almostLinear" },
            workspaces = { 1, 1.94, "almostLinear", "fade" },
            workspacesIn = { 1, 1.21, "almostLinear", "fade" },
            workspacesOut = { 1, 1.94, "almostLinear", "fade" },
        },
    },
})

-- Ref https://wiki.hyprland.org/Configuring/Workspace-Rules/

-- "Smart gaps" / "No gaps when only"

-- uncomment all if you wish to use that.

-- workspace = w[tv1], gapsout:0, gapsin:0

-- workspace = f[1], gapsout:0, gapsin:0

-- windowrule = border_size 0, match:floating 0, match:workspace w[tv1]

-- windowrule = rounding 0, match:floating 0, match:workspace w[tv1]

-- windowrule = border_size 0, match:floating 0, match:workspace f[1]

-- windowrule = rounding 0, match:floating 0, match:workspace f[1]

-- workspace 1 always belongs to eDP-1

-- if DP-2 is connected, workspace 2-9 belongs to DP-2

hl.workspace_rule({
    workspace = 1,
    monitor = "eDP-1",
    -- preferred (unrecognized workspace param)
})

hl.workspace_rule({
    workspace = 2,
    monitor = "DP-2",
    -- preferred (unrecognized workspace param)
})

hl.workspace_rule({
    workspace = 3,
    monitor = "DP-2",
    -- preferred (unrecognized workspace param)
})

hl.workspace_rule({
    workspace = 4,
    monitor = "DP-2",
    -- preferred (unrecognized workspace param)
})

hl.workspace_rule({
    workspace = 5,
    monitor = "DP-2",
    -- preferred (unrecognized workspace param)
})

hl.workspace_rule({
    workspace = 6,
    monitor = "DP-2",
    -- preferred (unrecognized workspace param)
})

hl.workspace_rule({
    workspace = 7,
    monitor = "DP-2",
    -- preferred (unrecognized workspace param)
})

hl.workspace_rule({
    workspace = 8,
    monitor = "DP-2",
    -- preferred (unrecognized workspace param)
})

hl.workspace_rule({
    workspace = 9,
    monitor = "DP-2",
    -- preferred (unrecognized workspace param)
})

-- See https://wiki.hyprland.org/Configuring/Dwindle-Layout/ for more

hl.config({
    dwindle = {
        -- pseudotile = true # Master switch for pseudotiling. Enabling is bound to mainMod + P in the keybinds section below
        preserve_split = true,
        -- You probably want this
    },
})

-- See https://wiki.hyprland.org/Configuring/Master-Layout/ for more

hl.config({
    master = {
        new_status = "master",
    },
})

-- https://wiki.hyprland.org/Configuring/Variables/#misc

hl.config({
    misc = {
        force_default_wallpaper = 0,
        -- Set to 0 or 1 to disable the anime mascot wallpapers
        disable_hyprland_logo = true,
        -- If true disables the random hyprland logo / anime girl background. :(
    },
})

--############

--## INPUT ###

--############

-- https://wiki.hyprland.org/Configuring/Variables/#input

hl.config({
    input = {
        kb_layout = "us",
        kb_options = "caps:ctrl_modifier",
        follow_mouse = 1,
        sensitivity = 0,
        -- -1.0 - 1.0, 0 means no modification.
        touchpad = {
            natural_scroll = true,
        },
    },
})

-- https://wiki.hyprland.org/Configuring/Variables/#gestures

-- gestures {

--     workspace_swipe = true

-- }

-- Example per-device config

-- See https://wiki.hyprland.org/Configuring/Keywords/#per-device-input-configs for more

hl.device({
    name = "epic-mouse-v1",
    sensitivity = -0.5,
})

--##################

--## KEYBINDINGS ###

--##################

-- See https://wiki.hyprland.org/Configuring/Keywords/

local mainMod = "SUPER"

-- Sets "Windows" key as main modifier

-- Example binds, see https://wiki.hyprland.org/Configuring/Binds/ for more

hl.bind(mainMod .. " + " .. "Return", hl.dsp.exec_cmd("ghostty"))

hl.bind(mainMod .. " + " .. "Q", hl.dsp.window.close())

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "E", hl.dsp.exit())

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "B", hl.dsp.exec_cmd("killall waybar && waybar"))

hl.bind("SUPER" .. " + " .. "V", hl.dsp.exec_cmd('cliphist list | rofi -dmenu | cliphist decode | wl-copy'))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "S", hl.dsp.exec_cmd(screenshot))

hl.bind(mainMod .. " + " .. "T", hl.dsp.exec_cmd("thunar"))

hl.bind(mainMod .. " + " .. "S", hl.dsp.exec_cmd(starDict))

hl.bind(mainMod .. " + " .. "E", hl.dsp.exec_cmd("rofi -modi emoji -show emoji"))

hl.bind(mainMod .. " + " .. "F", hl.dsp.window.fullscreen())

hl.bind(mainMod .. " + " .. "O", hl.dsp.window.float())

hl.bind(mainMod .. " + " .. "SPACE", hl.dsp.exec_cmd("rofi -show drun"))

hl.bind(mainMod .. " + " .. "G", hl.dsp.exec_cmd("google-chrome-stable"))

hl.bind(mainMod .. " + " .. "X", hl.dsp.exec_cmd("hyprlock"))

hl.bind(mainMod .. " + " .. "P", hl.dsp.window.pseudo())

-- dwindle

-- bind = $mainMod, I, togglesplit, # dwindle

-- Move focus with mainMod + arrow keys

hl.bind(mainMod .. " + " .. "H", hl.dsp.focus({ direction = "left" }))

hl.bind(mainMod .. " + " .. "L", hl.dsp.focus({ direction = "right" }))

hl.bind(mainMod .. " + " .. "K", hl.dsp.focus({ direction = "up" }))

hl.bind(mainMod .. " + " .. "J", hl.dsp.focus({ direction = "down" }))

-- Switch workspaces with mainMod + [0-9]

hl.bind(mainMod .. " + " .. 1, hl.dsp.focus({ workspace = 1 }))

hl.bind(mainMod .. " + " .. 2, hl.dsp.focus({ workspace = 2 }))

hl.bind(mainMod .. " + " .. 3, hl.dsp.focus({ workspace = 3 }))

hl.bind(mainMod .. " + " .. 4, hl.dsp.focus({ workspace = 4 }))

hl.bind(mainMod .. " + " .. 5, hl.dsp.focus({ workspace = 5 }))

hl.bind(mainMod .. " + " .. 6, hl.dsp.focus({ workspace = 6 }))

hl.bind(mainMod .. " + " .. 7, hl.dsp.focus({ workspace = 7 }))

hl.bind(mainMod .. " + " .. 8, hl.dsp.focus({ workspace = 8 }))

hl.bind(mainMod .. " + " .. 9, hl.dsp.focus({ workspace = 9 }))

hl.bind(mainMod .. " + " .. 0, hl.dsp.focus({ workspace = 10 }))

-- Move active window to a workspace with mainMod + SHIFT + [0-9]

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. 1, hl.dsp.window.move({ workspace = 1 }))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. 2, hl.dsp.window.move({ workspace = 2 }))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. 3, hl.dsp.window.move({ workspace = 3 }))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. 4, hl.dsp.window.move({ workspace = 4 }))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. 5, hl.dsp.window.move({ workspace = 5 }))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. 6, hl.dsp.window.move({ workspace = 6 }))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. 7, hl.dsp.window.move({ workspace = 7 }))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. 8, hl.dsp.window.move({ workspace = 8 }))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. 9, hl.dsp.window.move({ workspace = 9 }))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. 0, hl.dsp.window.move({ workspace = 10 }))

-- Example special workspace (scratchpad)

hl.bind(mainMod .. " + " .. "M", hl.dsp.workspace.toggle_special("magic"))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "M", hl.dsp.window.move({ workspace = "special:magic" }))

-- Scroll through existing workspaces with mainMod + scroll

hl.bind(mainMod .. " + " .. "mouse_down", hl.dsp.focus({ workspace = "e+1" }))

hl.bind(mainMod .. " + " .. "mouse_up", hl.dsp.focus({ workspace = "e-1" }))

-- Move/resize windows with mainMod + LMB/RMB and dragging

hl.bind(mainMod .. " + " .. "mouse:272", hl.dsp.window.drag(), { mouse = true })

hl.bind(mainMod .. " + " .. "mouse:273", hl.dsp.window.resize(), { mouse = true })

-- Laptop multimedia keys for volume and LCD brightness

hl.bind("XF86AudioRaiseVolume", hl.dsp.exec_cmd("wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%+"), { locked = true })

-- bindel = ,XF86AudioRaiseVolume, exec, $HOME/stow/dunst/.config/dunst/volume.sh raise_volume

hl.bind("XF86AudioLowerVolume", hl.dsp.exec_cmd("wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-"), { locked = true })

-- bindel = ,XF86AudioLowerVolume, exec, $HOME/stow/dunst/.config/dunst/volume.sh lower_volume

hl.bind("XF86AudioMute", hl.dsp.exec_cmd("wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle"), { locked = true })

-- bindel = ,XF86AudioMute, exec, $HOME/stow/dunst/.config/dunst/volume.sh mute_volume

hl.bind("XF86AudioMicMute", hl.dsp.exec_cmd("wpctl set-mute @DEFAULT_AUDIO_SOURCE@ toggle"), { locked = true })

-- bindel = ,XF86AudioMicMute, exec, $HOME/stow/dunst/.config/dunst/volume.sh mute_mic

-- bindel = ,XF86MonBrightnessUp, exec, brightnessctl s 10%+

hl.bind("XF86MonBrightnessUp", hl.dsp.exec_cmd(os.getenv("HOME") .. "/stow/dunst/.config/dunst/backlight.sh increase"), { locked = true })

-- bindel = ,XF86MonBrightnessDown, exec, brightnessctl s 10%-

hl.bind("XF86MonBrightnessDown", hl.dsp.exec_cmd(os.getenv("HOME") .. "/stow/dunst/.config/dunst/backlight.sh decrease"), { locked = true })

-- Requires playerctl

hl.bind("XF86AudioNext", hl.dsp.exec_cmd("playerctl next"), { locked = true })

hl.bind("XF86AudioPause", hl.dsp.exec_cmd("playerctl play-pause"), { locked = true })

hl.bind("XF86AudioPlay", hl.dsp.exec_cmd("playerctl play-pause"), { locked = true })

hl.bind("XF86AudioPrev", hl.dsp.exec_cmd("playerctl previous"), { locked = true })

--#############################

--## WINDOWS AND WORKSPACES ###

--#############################

-- See https://wiki.hyprland.org/Configuring/Window-Rules/ for more

-- See https://wiki.hyprland.org/Configuring/Workspace-Rules/ for workspace rules

-- Example windowrule v1 (old syntax - deprecated in v0.53)

-- windowrule = float, class:^(thunar)$

-- Example windowrule v2 (new syntax)

hl.window_rule({
    float = true,
    match = {
        class = "^(thunar)$",
    },
})

hl.window_rule({
    float = true,
    match = {
        class = "Alacritty",
    },
})

hl.window_rule({
    name  = "size_25__25_",
    match = {
        class = "Alacritty",
        title = "Alacritty",
    },
    size = "25% 25%",
})

hl.window_rule({
    float = true,
    match = {
        class = "thunar",
    },
})

hl.window_rule({
    name  = "size_60__60_",
    match = {
        class = "thunar",
    },
    size = "60% 60%",
})

hl.window_rule({
    float = true,
    match = {
        class = "org.pulseaudio.pavucontrol",
    },
})

hl.window_rule({
    name  = "size_60__60_",
    match = {
        class = "org.pulseaudio.pavucontrol",
    },
    size = "60% 60%",
})

-- Ignore maximize requests from apps. You'll probably like this.

hl.window_rule({
    suppress_maximize = true,
    match = {
        class = ".*",
    },
})

-- Fix some dragging issues with XWayland

-- windowrule = no_focus on, match:class ^$, match:title ^$, match:xwayland 1, match:floating 1, match:fullscreen 0, match:pin 0

-- Autostart
hl.on("hyprland.start", function()
    hl.exec_cmd("ghostty")
    hl.exec_cmd("nm-applet &")
    hl.exec_cmd("waybar")
    hl.exec_cmd("hyprpaper")
    hl.exec_cmd("hypridle")
    hl.exec_cmd("wl-paste --type text --watch cliphist store")
    hl.exec_cmd("wl-paste --type image --watch cliphist store")
end)

-- Exec (run every reload)
hl.on("config.reloaded", function()
    hl.exec_cmd("fcitx5 -d")
end)
